name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Compilar APK con Buildozer Action
        uses: ArtemSydoryk/buildozer-action@v1
        with:
          command: buildozer -v android debug
          buildozer_version: master

      - name: Guardar APK generado
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: bin/*.apk
